### ISSUE TITLE
Choose a content license

### ISSUE THREAD

**Issue by bradweikel** [codeforabq/codeforabq.github.io#1]
The Wordpress version of the codeforabq site had a generic copyright statement in the footer, which I've removed. We probably want to license our content more permissively. Code For America uses CC-BY-SA, which I think is appropriate, but I don't want to make a unilateral decision.

(Note: I've added CC-BY-SA for now)

**Comment by Smallmelo** [comment]
I think CC-BY-SA seems appropriate, too.

**Comment by bradweikel** [comment]
Two votes = decision :)
