### ISSUE TITLE
AGOL voucher info has been lost

### ISSUE THREAD

**Issue by jgravois** [codeforabq/codeforabq.github.io#10]
do the instructions we wrote up in https://github.com/codeforabq/Brigade-Brain/tree/master/Licenses/AGOL still exist anywhere?  

even including the info in a reply to this issue would be enough for me to point other brigades at.

cc/ @Smallmelo

**Comment by bradweikel** [comment]
It was moved to this repo's wiki:

https://github.com/codeforabq/Code-for-ABQ/wiki/Obtaining-ArcGIS-Online-Credits-For-Your-Brigade
