### ISSUE TITLE
Switch DNS from Dreamhost to Github

### ISSUE THREAD

**Issue by bradweikel** [codeforabq/codeforabq.github.io#2]
I'm more or less ready to switch us over to GitHub Pages. Preview the page here:
http://codeforabq.github.io/codeforabq.org

It's not perfect, but let's sort out any problems in the issue queue after it's live.

One question I'd like to resolve before migrating:
This repo is currently named "codeforabq.github.io", because that was the easiest way to get it up and running. Do we want to rename it codeforabq.org, so it's more clear what's housed in it? I lean towards yes, but with some ambivalence. The switch wouldn't be a very big deal... just need to create a new branch and reconfigure GitHub pages.

My other concern is whether Dreamhost will be fussy about switching the DNS to an external host. I've never used them as a registrar. Are they cool with changes like this, or will we need to transfer the registration to another registrar?

**Comment by Smallmelo** [comment]
I'm currently in the processing of transferring DNS records out of Dreamhost for the first time.  My experience transferring INTO Dreamhost was that it took 5 days.  I'll revisit this thread after the process is complete.

Changing the name of the repo to codeforabq.org seems like a good idea.  Go for it.

**Comment by bradweikel** [comment]
Do you mean changing registrars, or just changing DNS?

**Comment by bradweikel** [comment]
I've switched the repo name to "codeforabq.org" and made sure it's working. It broke the paths for some CSS and images, but I'll fix that when I'm back at my desk.

New preview url is:
http://codeforabq.github.io/codeforabq.org

**Comment by Smallmelo** [comment]
Ah, yes.  Let's make sure we are talking about the same thing.  I'm talking about changing the DNS records so that the site will be "hosted" by Github, but the domain will still be registered with our account at Dreamhost. We will stay pay the $10/year to have the domain registered at Dreamost.  We just won't be paying for hosting. So keeping registrars with Dreamhost, dropping our hosting account, and changing the DNS to point to Github.

**Comment by bradweikel** [comment]
OK, we're on the same page. I was confused by the "5 days" comment -- that's obscenely long for DNS changes. The old default was 24 hours, but increasingly I see people doing just a few hours. 

Anyway, I just logged into dreamhost and realized they are hosting our email accounts, too. How should we liberate ourselves from their hosted email? If the mothership can help us get gmail via Google Apps, that would be ideal. If not, Zoho is a suitable knockoff and they have a pretty sizable free tier.

**Comment by Smallmelo** [comment]
it looks like we can sign up for [Google App for Nonprofits](http://forum.codeforamerica.org/t/free-email-for-your-brigade-google-apps-and-office-365/172).  Once setup, we can points our records there.  Want me to get the ball rolling with that?  Or do you want to?

**Comment by bradweikel** [comment]
Unless something has changed recently, Google's pretty strict about only giving it to registered 501c3s, which is why I was asking if we can get it through the mothership.

**Comment by Smallmelo** [comment]
The link I provided above takes you to CFA's directions for applying for Google Apps for Nonprofits using their 501c3 number.  I should have clarified.

**Comment by bradweikel** [comment]
Oh awesome. I should have clicked. :)

Yes, go for it.

**Comment by bradweikel** [comment]
Update since our meeting: 

I got a little sneaky and figured out how to switch our DNS over to CloudFlare without disrupting our Dreamhost hosting. Then I switched the records for the website only, so it's now being served via GitHub Pages but email is still being served via Dreamhost for now. I'll open a new issue for that in the Brain.
